Afspelen audio
ICTOOSDDE3/Windefy pull request #8
Opened 2020-11-23 15:10 UTC by TheYAW21

2020-11-23 15:12 UTC, Nick-de-Bruin requested changes
- Write comments and summaries on functions

2020-11-23 15:53 UTC, DylanMRoubos approved these changes
Looks good enough to merge to develop

2020-11-26 08:22 UTC, Nick-de-Bruin submitted a review, later dismissed

2020-11-26 09:32 UTC, Mayntri approved these changes, later dismissed

2020-11-26 09:37 UTC, Nick-de-Bruin requested changes
Fix merge

2020-11-26 09:50 UTC, Nick-de-Bruin approved these changes

2020-11-26 09:50 UTC, merged